name: on main push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  oven-bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dockertest
