name: on release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  testing-env:
    runs-on: ubuntu-latest
    environment: argocd
    steps:
      - name: test
        run: echo "BWHAUHUAHWUHAWUH EVERYTHING IS DONE"
